name: star_transform
blocks:
  - name: trainer1
    type: fms-hf-tuning
    # training args
    learning_rate: 0.0001
    fp16: true
    logging_steps: 100
    save_steps: 50
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    max_steps: 100
target:
  name: cot_transform
  blocks:
    - name: llm1
      type: vllm-server
      decoding_method: sample
      temperature: 0.5
      max_new_tokens: 128
      min_new_tokens: 1
      model_id_or_path: /dccstor/gma/hf_models/mistralai/Mistral-7B-Instruct-v0.2
    - name: val1
      type: always_true
metadata:
  version: 1.0
