name: star_transform
blocks:
  - name: trainer1
    type: fms-hf-tuning
    config_path: /dccstor/cfm-tst/fms-sdg/fms_dgt/databuilders/transformation/star/trainer_configs/ds_config.json
    # training args
    learning_rate: 0.0001
    fp16: true
    logging_steps: 100
    save_steps: 50
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    max_steps: 100
target:
  name: cot_transform
  blocks:
    - name: llm1
      type: vllm-server
      decoding_method: sample
      temperature: 0.5
      max_new_tokens: 1024
      min_new_tokens: 1
      model_id_or_path: ibm-granite--granite-8b-code-instruct
    - name: val1
      type: always_true
metadata:
  version: 1.0
