databuilders:
  api_function_checking:
    blocks:
      - name: llm1
        type: vllm
        temperature: 0.5
        model_id_or_path: <model-path-here>
      - name: val2
        filter: true
        threshold: 0.9
tasks:
  api_yes_no:
    datastore:
      type: default
      output_dir: output/test_yes_no
task_files:
  - data/generation/code/apis/glaive/detection/multiple_apis/qna.yaml
  - data/generation/code/apis/glaive/detection/single_api/qna.yaml
  - data/generation/code/apis/glaive/detection/yes_no/qna.yaml
  - data/generation/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
  - data/generation/code/apis/glaive/sequencing/parallel_single/qna.yaml
parallel_config:
  api_function_checking:
    llm1:
      num_workers: 1
      num_cpus: 2
      num_gpus: 2
