databuilders:
  api_function_checking:
    blocks:
      - name: llm1
        type: vllm-server
        temperature: 0.5
        model_id_or_path: < path to model, e.g., .cache/huggingface/hub/models--ibm-granite--granite-8b-code-instruct/snapshots/... >
        parallel_config:
          num_workers: 2
          num_cpus_per_worker: 2
          num_gpus_per_worker: 1
          worker_configs:
            - workers: [0]
              port: 8001
            - workers: [1]
              port: 8002
      - name: val2
        filter: true
        threshold: 0.9
  api_yes_no_detection:
    blocks:
      - name: llm1
        type: vllm-server
        temperature: 0.5
        model_id_or_path: < path to model, e.g., .cache/huggingface/hub/models--ibm-granite--granite-8b-code-instruct/snapshots/... >
        parallel_config:
          num_workers: 2
          num_cpus_per_worker: 2
          num_gpus_per_worker: 1
          worker_configs:
            - workers: [0]
              port: 8001
            - workers: [1]
              port: 8002
tasks:
  api_yes_no:
    datastore:
      type: default
      output_dir: output/test_yes_no
task_files:
  - data/generation/code/apis/glaive/detection/multiple_apis/qna.yaml
  - data/generation/code/apis/glaive/detection/single_api/qna.yaml
  - data/generation/code/apis/glaive/detection/yes_no/qna.yaml
  - data/generation/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
  - data/generation/code/apis/glaive/sequencing/parallel_single/qna.yaml
